spring:
  application:
    name: zipurl

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name=com: com.mysql.cj.jdbc.Driver


  # Jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #Redis
  redis:
    host: localhost
    port: 6379