zipurl:
  short-id-size: 8
  url-prefix: https://zipurl.short/

spring:
  application:
    name: zipurl

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 10000

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 2s

# Resilience 4j configuration
resilience4j:
  circuitbreaker:
    instances:
      redisError:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      dbError:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  ratelimiter:
    instances:
      createShortUrlLimiter:
        limit-for-period: 5
        limit-refresh-period: 30s
        timeout-duration: 0